apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    app: back
  name: back
spec:
  replicas: 1
  strategy: {}
  selector:
      matchLabels:
          app: back
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: back
    spec:
      containers:
      - image: docker.io/amine142/php:latest
        name: back
        ports:
        - containerPort: 8082
        resources: {}
        tty: true
      hostname: backend
      restartPolicy: Always
status: {}
